FROM python:3.9-slim

WORKDIR /app

# Install dependencies
COPY kafka-producer/requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copy application code
COPY kafka-producer/*.py .

# Run the producer
CMD ["python", "gpuz_producer.py"]
