apiVersion: v1
kind: ConfigMap
metadata:
  name: hadoop-env
  namespace: gpu-monitoring
data:
  CORE_CONF_fs_defaultFS: "hdfs://namenode:9000"
  HDFS_CONF_dfs_replication: "1"
---
apiVersion: v1
kind: Service
metadata:
  name: namenode
  namespace: gpu-monitoring
spec:
  ports:
    - port: 9870
      targetPort: 9870
      name: web
    - port: 9000
      targetPort: 9000
      name: fs
  selector:
    app: namenode
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: namenode
  namespace: gpu-monitoring
spec:
  serviceName: namenode
  replicas: 1
  selector:
    matchLabels:
      app: namenode
  template:
    metadata:
      labels:
        app: namenode
    spec:
      containers:
        - name: namenode
          image: bde2020/hadoop-namenode:2.0.0-hadoop3.2.1-java8
          ports:
            - containerPort: 9870
            - containerPort: 9000
          env:
            - name: CLUSTER_NAME
              value: "gpu-monitoring"
          envFrom:
            - configMapRef:
                name: hadoop-env
          volumeMounts:
            - name: namenode-data
              mountPath: /hadoop/dfs/name
  volumeClaimTemplates:
    - metadata:
        name: namenode-data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 10Gi
---
apiVersion: v1
kind: Service
metadata:
  name: datanode
  namespace: gpu-monitoring
spec:
  ports:
    - port: 9864
      targetPort: 9864
      name: web
  selector:
    app: datanode
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: datanode
  namespace: gpu-monitoring
spec:
  serviceName: datanode
  replicas: 1
  selector:
    matchLabels:
      app: datanode
  template:
    metadata:
      labels:
        app: datanode
    spec:
      containers:
        - name: datanode
          image: bde2020/hadoop-datanode:2.0.0-hadoop3.2.1-java8
          ports:
            - containerPort: 9864
          envFrom:
            - configMapRef:
                name: hadoop-env
          volumeMounts:
            - name: datanode-data
              mountPath: /hadoop/dfs/data
  volumeClaimTemplates:
    - metadata:
        name: datanode-data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 50Gi
