apiVersion: v1
kind: Service
metadata:
  name: spark-master
  namespace: gpu-monitoring
spec:
  ports:
    - port: 8080
      targetPort: 8080
      name: web
    - port: 7077
      targetPort: 7077
      name: spark
  selector:
    app: spark-master
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: spark-master
  namespace: gpu-monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spark-master
  template:
    metadata:
      labels:
        app: spark-master
    spec:
      containers:
        - name: spark-master
          image: apache/spark:3.5.0
          command: ["/bin/bash", "-c"]
          args:
            - |
              unset SPARK_MASTER_PORT SPARK_MASTER_WEBUI_PORT
              /opt/spark/sbin/start-master.sh --host 0.0.0.0 --port 7077 --webui-port 8080
              tail -f /dev/null
          ports:
            - containerPort: 8080
            - containerPort: 7077
          volumeMounts:
            - name: spark-jobs
              mountPath: /opt/spark-jobs
      volumes:
        - name: spark-jobs
          persistentVolumeClaim:
            claimName: spark-jobs-pvc
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: spark-worker
  namespace: gpu-monitoring
spec:
  replicas: 2
  selector:
    matchLabels:
      app: spark-worker
  template:
    metadata:
      labels:
        app: spark-worker
    spec:
      containers:
        - name: spark-worker
          image: apache/spark:3.5.0
          command: ["/bin/bash", "-c"]
          args:
            - |
              /opt/spark/sbin/start-worker.sh spark://spark-master:7077
              tail -f /dev/null
          env:
            - name: SPARK_WORKER_MEMORY
              value: "2G"
            - name: SPARK_WORKER_CORES
              value: "2"
          volumeMounts:
            - name: spark-jobs
              mountPath: /opt/spark-jobs
      volumes:
        - name: spark-jobs
          persistentVolumeClaim:
            claimName: spark-jobs-pvc
