apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: spark-jobs-pvc
  namespace: gpu-monitoring
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: hostpath
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gpu-data-pvc
  namespace: gpu-monitoring
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: hostpath
